### ISSUE TITLE
Brew Install Fails

### ISSUE THREAD

**Issue by cholick** [nebhale/cf-build#1]
A homebrew install, per the instructions, fails

```
➜  ~  brew install cf-build
==> Installing cf-build from nebhale/homebrew-personal
Error: No available formula for cloudfoundry-cli (dependency of nebhale/personal/cf-build)
```

Have you tapped some other repository that has cloudfoundry-cli that's not part of the instructions?

**Comment by nebhale** [comment]
Yup, you're absolutely right.  You need the [Pivotal Tap](https://github.com/pivotal/homebrew-tap).  I'll update the docs with that.
